export const ROUTES = {
  public: {
    home: "/",
    centers: "/centers",
    contact: "/contact",
    postnatalCare: "/discover/postnatal-care",
    prenatalCare: "/discover/prenatal-care",
    babyCare: "/discover/baby-care",
    womensWellness: "/discover/womens-wellness",
    ayurvedicWellness: "/discover/ayurvedic-wellness",
    onlineConsultation: "/discover/online-consultation",
    whoWeAre: "/about/who-we-are",
    howAyursargaWorks: "/about/how-ayursarga-works",
    whyAyursarga: "/about/why-ayursarga",
    missionVision: "/mission-vision",
  },
  consumer: {
    home: "/app",
    bookings: "/app/bookings",
    completeProfile: "/app/complete-profile",
    login: "/app/login",
  },
  hospital: {
    home: "/hospital",
    profile: "/hospital/profile",
    services: "/hospital/services",
    bookings: "/hospital/bookings",
    availability: "/hospital/availability",
    changePassword: "/hospital/change-password",
    login: "/hospital/login",
    forgotPassword: "/hospital/forgot-password",
  },
  admin: {
    home: "/admin",
    hospitals: "/admin/hospitals",
    consultants: "/admin/consultants",
    users: "/admin/users",
    bookings: "/admin/bookings",
    availability: "/admin/availability",
    audits: "/admin/audits",
    login: "/admin/login",
    forgotPassword: "/admin/forgot-password",
  },
} as const;
