export const ROUTES = {
  public: {
    home: "/",
    centers: "/centers",
    contact: "/contact",
    postnatalCare: "/discover/postnatal-care",
    prenatalCare: "/discover/prenatal-care",
    babyCare: "/discover/baby-care",
    womensWellness: "/discover/womens-wellness",
    missionVision: "/mission-vision",
  },
  consumer: {
    home: "/app",
    bookings: "/app/bookings",
    profile: "/app/profile",
    completeProfile: "/app/complete-profile",
    login: "/app/login",
    register: "/app/register",
    forgotPassword: "/app/forgot-password",
  },
  hospital: {
    home: "/hospital",
    profile: "/hospital/profile",
    services: "/hospital/services",
    bookings: "/hospital/bookings",
    changePassword: "/hospital/change-password",
    login: "/hospital/login",
    forgotPassword: "/hospital/forgot-password",
  },
  admin: {
    home: "/admin",
    hospitals: "/admin/hospitals",
    users: "/admin/users",
    bookings: "/admin/bookings",
    audits: "/admin/audits",
    login: "/admin/login",
    forgotPassword: "/admin/forgot-password",
  },
} as const;
